name = "SpacecraftBuilder"
uuid = "92ba2ec4-d08f-4ce1-9cdf-fe8c7bb13e53"
version = "0.1.0"
authors = ["F. Capolupo"]

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
JTools = "ab7590e3-7970-434e-bf9d-2a5e455e45fa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Quats = "faa667c8-0f2e-4834-a931-554d4b02f32e"

[sources]
JTools = {rev = "master", url = "C:\\Users\\francesco capolupo\\OneDrive - ESA\\Desktop\\Work\\Tools\\ToolsJulia\\Packages\\JTools"}
Quats = {rev = "master", url = "C:\\Users\\francesco capolupo\\OneDrive - ESA\\Desktop\\Work\\Tools\\ToolsJulia\\Packages\\Quats"}

[compat]
Quats = "0.1.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
